on:
  push:
    branches:
    - main 
  pull_request:
    branches:
    - main
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.25.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Run tests
      run: go test -v ./...
